name: pytest
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv codecov pytest pytest-cov pytest-mock pytest-subtests
        pip install -r requirements.txt
        pipenv install --dev
    - name: Install bedtools
      run: |
        wget https://github.com/arq5x/bedtools2/releases/download/v2.31.0/bedtools.static -O bedtools
        chmod a+x bedtools
        sudo mv bedtools /usr/bin/bedtools

        bedtools
    - name: Test with pytest
      run: |
        pytest -vv --cov .
